/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Example1 */

#ifndef _Included_Example1
#define _Included_Example1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Example1
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Example1_foo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
